config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'

  post 'city/find'
  post 'city/update'

  post 'lobster/find'
  post 'ban/find'

  resources :state, :city, :ban, :lobster, :composter, :customer, :facility

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ban.rb
# frozen_string_literal: true

class Ban < ApplicationRecord
  belongs_to :city
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  belongs_to :state
  has_one :ban
  has_one :facility
  has_many :lobsters
  has_many :customers
  has_many :composters
end

app/models/composter.rb
# frozen_string_literal: true

class Composter < ApplicationRecord
  belongs_to :city
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :city
end

app/models/facility.rb
# frozen_string_literal: true

class Facility < ApplicationRecord
  belongs_to :city
end

app/models/lobster.rb
# frozen_string_literal: true

class Lobster < ApplicationRecord
  belongs_to :city
end

app/models/state.rb
# frozen_string_literal: true

class State < ApplicationRecord
  has_many :cities
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/ban_controller.rb
# frozen_string_literal: true

class BanController < ApplicationController
  def all
    render json: Ban.all
  end

  def show
    ban = Ban.find(params[:id])
    render json: ban
  end

  def update
    allowed_params = params.permit(:ban_type, :ban_stage, :enacted, :proposed)
    Ban.update(params[:id], allowed_params)
  end
end

app/controllers/city_controller.rb
# frozen_string_literal: true

class CityController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    @city = City.find(params[:id])
  end

  def find
    @find_result = City.where("name like '%#{params[:name]}%'").limit(10)
  end

  def update
    allowed_params = params.permit(
      :name,
      :latitude,
      :longitude,
      :population,
      :zips,
      :density,
      :county
    )
    @city = City.update(params[:id], allowed_params)
  end

  private

  def create_response_hash(city)
    {
      city: city,
      ban: city.ban,
      lobsters: city.lobsters,
      facility: city.facility,
      customers: city.customers,
      composters: city.composters
    }
  end
end

app/controllers/composter_controller.rb
# frozen_string_literal: true

class ComposterController < ApplicationController
  def update
    allowed_params = params.permit(:name, :url, :email, :phone, :active)
    Composter.update(params[:id], allowed_params)
  end
end

app/controllers/customer_controller.rb
# frozen_string_literal: true

class CustomerController < ApplicationController
  def update
    allowed_params = params.permit(:zip)
    Customer.update(params[:id], allowed_params)
  end
end

app/controllers/facility_controller.rb
# frozen_string_literal: true

class FacilityController < ApplicationController
  def update
    allowed_params = params.permit(:name, :address, :postal_code, :capability)
    Lobster.update(params[:id], allowed_params)
  end
end

app/controllers/lobster_controller.rb
# frozen_string_literal: true

class LobsterController < ApplicationController
  def all
    render json: Ban.all
  end

  def show
    lobster = Lobster.find(params[:id])
    render json: lobster
  end

  def update
    allowed_params = params.permit(:zip, :address, :phone)
    Lobster.update(params[:id], allowed_params)
  end
end

app/controllers/state_controller.rb
class StateController < ApplicationController
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ActionController::Base
  def index
  end
end

app/views/city/find.html.erb
<h2>Results</h2>
<ul>
  <% @find_result.each do |city| %>
    <li style="margin-top: 1rem;">
      <h3><%= link_to "#{city.name}", city_path(city) %></h3>
    </li>
  <% end %>
</ul>

app/views/city/show.html.erb
<h2>Update Data for <%= @city.name %></h2>

<form id="city" method="post" action="update">
  <input type="number" name="id" id="city_id" hidden value="<%= @city.id %>">
  <div style="margin-top: 1rem;">
    <label for="name">Name</label>
    <input type="text" name="name" id="city_name" required value="<%= @city.name %>">
  </div>
  <div style="margin-top: 1rem;">
    <label for="latitude">Latitude</label>
    <input type="number" name="latitude" id="latitude" required value="<%= @city.latitude %>">
  </div>
  <div style="margin-top: 1rem;">
    <label for="longitude">Longitude</label>
    <input type="number" name="longitude" id="longitude" required value="<%= @city.longitude %>">
  </div>
  <div style="margin-top: 1rem;">
    <label for="population">Population</label>
    <input type="number" name="population" id="population" required value="<%= @city.population %>">
  </div>
  <div style="margin-top: 1rem;">
    <label for="density">Density</label>
    <input type="number" name="density" id="density" required value="<%= @city.density %>">
  </div>
  <div style="margin-top: 1rem;">
    <label for="zips">Zip Codes</label>
    <textarea name="zips" id="zips" required><%= @city.zips %></textarea>
  </div>
  <input style="margin-top: 1rem;" type="submit">
</form>
<% if @city.ban.present? %>
  <h3 style="margin-top: 3rem;">Ban Data</h3>
  <table>
    <tr>
      <td>Type</td><td><%= @city.ban.ban_type %></td>
    </tr>
    <tr>
      <td>Stage</td><td><%= @city.ban.stage %></td>
    </tr>
    <tr>
      <td>Propsed</td><td><%= @city.ban.proposed %></td>
    </tr>
    <tr>
      <td>Enacted</td><td><%= @city.ban.enacted %></td>
    </tr>
  </table>
<!--  <form id="ban" method="post"></form>-->
<% end %>
<% if @city.lobsters.present? %>
  <%= @city.lobsters.to_s %>
<!--  <form id="lobsters" method="post"></form>-->
<% end %>
<% if @city.composters.present? %>
  <%= @city.composters.to_s %>
<!--  <form id="composters" method="post"></form>-->
<% end %>
<% if @city.customers.present? %>
  <%= @city.customers.to_s %>
<!--  <form id="customers" method="post"></form>-->
<% end %>
<% if @city.facility.present? %>
  <%= @city.facility.to_s %>
<!--  <form id="facility" method="post"></form>-->
<% end %>

app/views/city/update.html.erb
<h2>Updated Data for <%= @city.name %></h2>
<table>
  <tr>
    <td>Coordinates</td><td><%= "#{@city.latitude}, #{@city.longitude}" %></td>
  </tr>
  <tr>
    <td>Population</td><td><%= @city.population %></td>
  </tr>
  <tr>
    <td>Density</td><td><%= @city.density %></td>
  </tr>
  <tr>
    <td>Zips</td><td><%= @city.zips %></td>
  </tr>
</table>
<a href="http://localhost:3000">Back to City Search</a>

app/views/welcome/index.html.erb
<h1>Better Earth DB</h1>

<form action="city/find" method="post">
  <div>
    <label for="name">Enter city name: </label>
    <input type="text" name="name" id="name" required>
  </div>
</form>